-- enrollment schedule DDL
CREATE TABLE ENROLLMENT_SCHEDULE (
    CAMPUS_ID INT,
    PHASE_ID INT,
    YEAR INT,
    SEMESTER INT,
    START_TIMESTAMP TIMESTAMP,
    END_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (CAMPUS_ID, PHASE_ID, YEAR, SEMESTER),
    FOREIGN KEY (CAMPUS_ID) REFERENCES CAMPI (CAMPUS_ID),
    FOREIGN KEY (PHASE_ID) REFERENCES PHASE (PHASE_ID)
);
