apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: pgadmin-claim0
  name: pgadmin-claim0
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: utfpr-chatbot-file
  resources:
    requests:
      storage: 100Mi
status: {}
