
name: utfpr_chatbot

services:
  rasa_server:
    container_name: rasa_server
    image: aurelixv/rasa_server:latest
    depends_on:
      rasa_actions:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks: ['net']
    restart: no
    command: run -vv --model models/nlu_utfpr_chatbot.tar.gz --credentials credentials_dev.yml -p 5005
    working_dir: /app
    volumes:
      - ./bot:/app
    ports:
      - 5005:5005
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://0.0.0.0:5005/ || exit 1"]
      interval: 1s
      timeout: 5s
      retries: 5

  rasa_actions:
    container_name: rasa_actions
    image: aurelixv/rasa_actions:latest
    depends_on:
      postgres:
        condition: service_healthy
    networks: ['net']
    restart: unless-stopped
    command: start -vv -p 5055 --actions actions
    volumes:
      - ./bot/actions:/app/actions
      - ./bot/endpoints.yml:/app/endpoints.yml
    ports:
      - 5055:5055
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://0.0.0.0:5055/health || exit 1"]
      interval: 1s
      timeout: 5s
      retries: 5

  postgres:
    container_name: postgres
    image: aurelixv/postgres:latest
    networks: ['net']
    restart: unless-stopped
    environment:
      POSTGRES_USER: "utfpr_chatbot"
      POSTGRES_PASSWORD: "utfpr_chatbot"
    volumes:
      - ./database/ingestion.sh:/docker-entrypoint-initdb.d/ingestion.sh
      - ./database/data_csv:/utfpr_chatbot/data
      - ./database/DDL:/utfpr_chatbot/DDL
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U utfpr_chatbot"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: pgadmin
    image: aurelixv/pgadmin:latest
    depends_on:
      postgres:
        condition: service_healthy
    networks: ['net']
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@utfpr-chatbot.com"
      PGADMIN_DEFAULT_PASSWORD: "utfpr_chatbot"
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
      - ./pgadmin/pgpass:/root/.pgadmin
    ports:
      - 8888:80

networks: {net: {}}
