-- enrollment schedule DDL
CREATE TABLE ENROLLMENT_SCHEDULE (
    CAMPUS_ID INT,
    ENROLLMENT_PHASE_ID INT,
    YEAR INT,
    SEMESTER INT,
    START_TIMESTAMP TIMESTAMP,
    END_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (CAMPUS_ID, ENROLLMENT_PHASE_ID, YEAR, SEMESTER),
    FOREIGN KEY (CAMPUS_ID) REFERENCES CAMPUS (CAMPUS_ID),
    FOREIGN KEY (ENROLLMENT_PHASE_ID) REFERENCES ENROLLMENT_PHASE (ENROLLMENT_PHASE_ID)
);
